
package systemlogic.processcentricservices.api.sw;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ApiService", targetNamespace = "http://sw.api.processcentricservices.systemlogic/", wsdlLocation = "https://api-introsde.herokuapp.com/ws/api?wsdl")
public class ApiService
    extends Service
{

    private final static URL APISERVICE_WSDL_LOCATION;
    private final static WebServiceException APISERVICE_EXCEPTION;
    private final static QName APISERVICE_QNAME = new QName("http://sw.api.processcentricservices.systemlogic/", "ApiService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api-introsde.herokuapp.com/ws/api?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APISERVICE_WSDL_LOCATION = url;
        APISERVICE_EXCEPTION = e;
    }

    public ApiService() {
        super(__getWsdlLocation(), APISERVICE_QNAME);
    }

    public ApiService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APISERVICE_QNAME, features);
    }

    public ApiService(URL wsdlLocation) {
        super(wsdlLocation, APISERVICE_QNAME);
    }

    public ApiService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APISERVICE_QNAME, features);
    }

    public ApiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApiService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Api
     */
    @WebEndpoint(name = "ApiImplPort")
    public Api getApiImplPort() {
        return super.getPort(new QName("http://sw.api.processcentricservices.systemlogic/", "ApiImplPort"), Api.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Api
     */
    @WebEndpoint(name = "ApiImplPort")
    public Api getApiImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sw.api.processcentricservices.systemlogic/", "ApiImplPort"), Api.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APISERVICE_EXCEPTION!= null) {
            throw APISERVICE_EXCEPTION;
        }
        return APISERVICE_WSDL_LOCATION;
    }

}
